/*****************************************************************************
 *                                                                           *
 * Copyright (c) 2018 Bichler Technologies GmbH. All rights reserved.        *
 *                                                                           *
 * Software License Agreement ("SLA") Version 1.0                            *
 *                                                                           *
 * !!!!This file was generated by Automation Studio, do not change it!!!     *
 *                                                                           *
 * Unless explicitly acquired and licensed from Licensor under another       *
 * license, the contents of this file are subject to the Software License    *
 * Agreement ("SLA") Version 2.6, or subsequent versions as allowed by the   *
 * SLA, and You may not copy or use this file in either source code or       *
 * executable form, except in compliance with the terms and conditions of    *
 * the SLA.                                                                  *
 *                                                                           *
 * All software distributed under the SLA is provided strictly on an "AS     *
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,       *
 * AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT      *
 * LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR   *
 * PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific   *
 * language governing rights and limitations under the SLA.                  *
 *                                                                           *
 * The complete license agreement can be found here:                         *
 * http://bichler.tech/License/SLA/1.0/                                      *
 *                                                                           *
 * btech_iec_program.c                                                       *
 *  Created on: May 22, 2018                                                 *
 *      Author: hannes                                                       *
 *                                                                           *
 *****************************************************************************/

#include "btech_iec_program.h"
#if 0
#include "task.h"

/******************************************************************
 *
 * this task may only take 10 microseconds, because we have to ensure
 * that the next iteration starts in time
 *
 ******************************************************************/
int Task_10mic()
{

	RT_TASK *task = malloc(sizeof(RT_TASK));
	rt_task_create(task, "iec_runtime" , 1,2,3);
//	int *var1 = &g_Global_Start_Memory[g_Global_Act_Var_Index];
//	g_Global_Act_Var_Index + 4;



	return 1;
}
#endif

void btech_init()
{
	/**
	 * initialize task structure
	 */
	//iec_main_task *g_IEC_Main_Task = malloc(sizeof(iec_main_task));
	//g_IEC_Main_Task->Task_10mic = Task_10mic;
}
